parameters:
#    hamdi_media.example.class: Hamdi\MediaBundle\Example

services:
#    hamdi_media.example:
#        class: %hamdi_media.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
