parameters:
#    hamdi_admin.example.class: Hamdi\AdminBundle\Example
     hamdi_admin.example.class: Portail\FrontBundle\Form\UserType
services:
#    hamdi_admin.example:
#        class: %hamdi_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

