<?php

namespace Portail\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheMaladieRepository extends EntityRepository
{
  
    public function getMaladieBy($lettre) {
        $qb = $this->createQueryBuilder('m')
                   ->select('m')
                  ->where('m.designation LIKE :lettre')
                  ->setParameter('lettre', $lettre.'%');

        return $qb->getQuery()
                  ->getResult();
    }
    public function getMaladieByMotCle($mot) {
        $qb = $this->createQueryBuilder('m')
                   ->select('m')
                  ->where('(m.designation LIKE :mot) or(m.description LIKE :mot) or (m.extrait LIKE :mot) or (m.symptomes LIKE :mot) or (m.causes LIKE :mot) or (m.symptomes LIKE :mot) or (m.prevention LIKE :mot)')
                  ->setParameter('mot', '%'.$mot.'%');

        return $qb->getQuery()
                  ->getResult();
    }
    public function selectcateg($id) {
          $qb = $this->createQueryBuilder('m')
                   ->select('m')
                  ->where('m.id!=:id')
                  ->setParameter('id',$id);

        return $qb->getQuery()
                  ->getResult();
        
    }
	public function getPlusLu($limit){
	 $qb = $this->createQueryBuilder('m')
                   ->select('m')
				   ->addOrderBy('m.nbvue', 'DESC')
				   ->setMaxResults($limit);
				 return $qb->getQuery()
                  ->getResult();
	}
	
	
	
}
