calendar_index:
    pattern:  /calendar
    defaults: { _controller: BladeTesterCalendarBundle:Event:index }
    
calendar_event_list:
    pattern:  /calendar/list
    defaults: { _controller: BladeTesterCalendarBundle:Event:list }

calendar_event_list_by_day:
    pattern:  /calendar/by_day/{year}/{month}/{day}
    defaults: { _controller: BladeTesterCalendarBundle:Event:listByDay }

calendar_event_list_by_week:
    pattern:  /calendar/by_week/{year}/{month}/{day}
    defaults: { _controller: BladeTesterCalendarBundle:Event:listByWeek }

calendar_event_list_by_month1:
    pattern:  /calendar/by_month/{year}/{month}/{idrdv}/{idexpediteur}
    defaults: { _controller: PortailCalendarBundle:Event:listByMonth}
#calendar_event_list_by_month5:
 #   pattern:  /calendar/by_month
   # defaults: { _controller: PortailCalendarBundle:Event:listByMonth }
calendar_by_user:
    pattern:  /calendar/by_month/{year}/{month}/{user}
    defaults: { _controller: PortailCalendarBundle:Event:listByUser}
  
calendar_event_add:
    pattern:  /calendar/add
    defaults: { _controller: PortailCalendarBundle:Event:add }
calendar_event_save:
    pattern:  /calendar/save
    defaults: { _controller: PortailCalendarBundle:Event:save }

calendar_event_edit:
    pattern:  /calendar/{id}/edit
    defaults: { _controller: BladeTesterCalendarBundle:Event:edit }

calendar_event_delete:
    pattern:  /calendar/{id}/delete
    defaults: { _controller: BladeTesterCalendarBundle:Event:delete }

calendar_mini_calendar:
    pattern:  /calendar/mini/{year}/{month}
    defaults: { _controller: BladeTesterCalendarBundle:Calendar:showMini }


calendar_category_edit:
    pattern: /calendar/category/{id}/edit
    defaults: { _controller: BladeTesterCalendarBundle:Category:edit }

calendar_category_delete:
    pattern: /calendar/category/{id}/delete
    defaults: { _controller: BladeTesterCalendarBundle:Category:delete }

calendar_category_add:
    pattern: /calendar/category/add
    defaults: { _controller: BladeTesterCalendarBundle:Category:add }


calendar_settings_update:
    pattern: /calendar/settings/update
    defaults: { _controller: BladeTesterCalendarBundle:Settings:update }
    requirements:
        _method:  POST

calendar_settings:
    pattern: /calendar/settings
    defaults: { _controller: BladeTesterCalendarBundle:Settings:index }
    requirements:
        _method:  GET
