parameters:
#    hamdi_partenaire.example.class: Hamdi\PartenaireBundle\Example

services:
#    hamdi_partenaire.example:
#        class: %hamdi_partenaire.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
