jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_AUTEUR:      ROLE_USER
        ROLE_MODERATEUR:  [ROLE_AUTEUR,ROLE_USER]
        ROLE_ADMIN:       [ROLE_MODERATEUR,ROLE_AUTEUR,ROLE_USER,ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        front:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path:     security_login_front 
                check_path:     checklogin
                default_target_path:    /portail/index
                csrf_provider: form.csrf_provider
            logout:
                path:   /logout
                target: /index
            anonymous:       true    
            logout:          true 

        admin:
            pattern: ^/admin
            form_login:                 
                provider:    fos_userbundle  
                login_path: /admin/login
                check_path:  checklogin
               
            logout:
                path:   /admin/logout
                target: /admin
            anonymous:       true   
            logout:          true   
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, role: ROLE_ADMIN }