portail_front_homepage:
    pattern:  /index
    defaults: { _controller: PortailNewsBundle:News:index }
contenu_comment:
    pattern: /comment
    defaults: { _controller: PortailFrontBundle:Default:voir }
listcomment:
    pattern: /listc
    defaults: { _controller: PortailFrontBundle:Default:listcomment }
fichemaladieadd:
    pattern: /fichemaladie
    defaults: { _controller: PortailFrontBundle:Fichemaladie:ajouter }
editfichemaladie:
    pattern: /editfichemaladie
    defaults: { _controller: PortailFrontBundle:Fichemaladie:edit } 
updatefichmaladie:
    pattern: /updatefichemaladie
    defaults: { _controller: PortailFrontBundle:Fichemaladie:update }
deletefichemaladie:
    pattern: /deletefichemaladie
    defaults: { _controller: PortailFrontBundle:Fichemaladie:delete } 
listmaladies:
    pattern: /listmaladies/{page}
    defaults: { _controller: PortailFrontBundle:Fichemaladie:list,page: 1 } 
detailmaladie:
    pattern: /maladie/{id}
    defaults: { _controller: PortailFrontBundle:Fichemaladie:detailmaladie } 
recherchealphamaladie:
  pattern: /recherchemaladiealphabet/{lettre}/{page}
  defaults: { _controller: PortailFrontBundle:Fichemaladie:rechercheparalphabet,lettre: 'A',page: 1 } 
rechercheparmotclemaladie:
  pattern: /rechercheparmot/{page}
  defaults: { _controller: PortailFrontBundle:Fichemaladie:rechercheparmotcle,page: 1 } 
listmaladiebycategory:
  pattern: /listmaladie/{souscategorie}/{page}
  defaults: { _controller: PortailFrontBundle:Fichemaladie:rechercheparsouscategorie,page: 1,souscategorie: 1 }  
  
    
    
contact:
   pattern: /contact
   defaults: { _controller: PortailFrontBundle:Default:contact }
envoicontact:
   pattern: /envoicontact
   defaults: { _controller: PortailBoiteBundle:BoiteReception:envoicontact }
  
blog:
   pattern: /blog1
   defaults: { _controller: PortailFrontBundle:Default:blog }  

checklogin:
  pattern: /logincheck
  defaults: { _controller: PortailFrontBundle:Security:check }
security_login_front:
  pattern: /login
  defaults: { _controller: PortailFrontBundle:Security:login }
security_logout:
  pattern: /logout
  defaults: { _controller: PortailFrontBundle:Security:logout }

fos_register:
  pattern: /register
  defaults: { _controller: PortailFrontBundle:Registration:register }
  requirements: { _method: post|get }
Testusername:
  pattern: /username
  defaults: { _controller: PortailFrontBundle:Registration:Testusername }

Testemail:
  pattern: /email
  defaults: { _controller: PortailFrontBundle:Registration:Testemail}
  
profilinfo:
  pattern: /profile
  defaults: { _controller: PortailFrontBundle:Registration:Profil}
editprofil:
  pattern: /modifprofil
  defaults: { _controller: PortailFrontBundle:Registration:Profil}

profilboite:
  pattern: /profilBoite
  defaults: { _controller: PortailBoiteBundle:BoiteReception:Boite}
uploadavatar:
  pattern: /uploadavatar
  defaults: { _controller: PortailFrontBundle:Registration:updateavatar}

   
user_registration_confirmed:
  pattern: /confirmer
  defaults: { _controller: PortailFrontBundle:Registration:confirmed }
  
fos_user_registration_confirm:
   pattern: /confirm/{token}
   defaults: { _controller: PortailFrontBundle:Registration:confirm } 
fos_user_registration_check_email:
   pattern: /check-Email/
   defaults: { _controller: PortailFrontBundle:Registration:checkEmail}
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile 

  
  
   