parameters:
#    portail_annuaire.example.class: Portail\AnnuaireBundle\Example

services:
#    portail_annuaire.example:
#        class: %portail_annuaire.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
