<?php

namespace Hamdi\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function MesMessages()
    {
        
       return $this->createQueryBuilder('p')
                    ->select('COUNT(v) as ')
                    ->where('msg_vue = 0');
                        
       
    }
}
